export enum GroupsParamsEnum {
    AWARDED_ADA = 'aa',
    AWARDED_USD = 'au',
    CAMPAIGNS = 'cam',
    COHORT = 'coh',
    COMMUNITIES = 'com',
    FUNDED_PROPOSALS = 'fp',
    FUNDS = 'f',
    LIMIT = 'l',
    PAGE = 'p',
    IDEASCALE_PROFILES = 'ip',
    QUERY = 'q',
    SORTS = 'st',
    TAGS = 't',
}
