export enum ProposalParamsEnum {
    AWARDED_ADA = 'aa',
    AWARDED_USD = 'au',
    BUDGETS = 'b',
    CATEGORIES = 'cat',
    CAMPAIGNS = 'cam',
    COHORT = 'coh',
    COMMUNITIES = 'com',
    FUNDS = 'f',
    FUNDING_STATUS = 'fs',
    GROUPS = 'g',
    LIMIT = 'l',
    MAX_BUDGET = 'bmax',
    MAX_PROJECT_LENGTH = 'lmax',
    MIN_BUDGET = 'bmin',
    PROJECT_LENGTH = 'pl',
    MIN_PROJECT_LENGTH = 'lmin',
    OPENSOURCE_PROPOSALS = 'op',
    PAGE = 'p',
    IDEASCALE_PROFILES = 'ip',
    PROJECT_STATUS = 'ps',
    QUERY = 'q',
    QUICK_PITCHES = 'qp',
    VIEW = 'v',
    SORTS = 'st',
    TAGS = 't',
    TYPE = 'pt',
}
