export enum ServiceWorkflowParams {
    STEP = 'step',
    SERVICE_HASH = 'serviceHash',
    EDIT = 'edit',
    TITLE = 'title',
    DESCRIPTION = 'description',
    TYPE = 'type',
    HEADER_IMAGE = 'header_image',
    HEADER_IMAGE_URL = 'header_image_url',
    CATEGORIES = 'categories',
    LOCATION = 'location',
    NAME = 'name',
    EMAIL = 'email',
    WEBSITE = 'website',
    GITHUB = 'github',
    LINKEDIN = 'linkedin',
}
