export enum TinderWorkflowParams {
    STEP = 'step',
    EDIT = 'edit',
    TINDER_COLLECTION_HASH = 'tinderCollectionHash',
    LEFT_BOOKMARK_COLLECTION_HASH = 'leftBookmarkCollectionHash',
    RIGHT_BOOKMARK_COLLECTION_HASH = 'rightBookmarkCollectionHash',
    SELECTED_FUND = 'selectedFund',
    PROPOSAL_TYPES = 'proposalTypes',
    PROPOSAL_SIZES = 'proposalSizes',
    IMPACT_TYPES = 'impactTypes',
    FUNDS = 'f',
    TITLE = 'title',
    CONTENT = 'content',
    VISIBILITY = 'visibility',
    COMMENTS_ENABLED = 'comments_enabled',
    COLOR = 'color',
    STATUS = 'status',
    SWIPED_LEFT_PROPOSALS = 'swipedLeftProposals',
    SWIPED_RIGHT_PROPOSALS = 'swipedRightProposals',
    CURRENT_INDEX = 'currentIndex',
    TOTAL_PROPOSALS_SEEN = 'totalProposalsSeen',
    PAGE = 'p',
    LOAD_MORE = 'loadMore',
    SAVED_CURRENT_INDEX = 'savedCurrentIndex',
    SAVED_TOTAL_SEEN = 'savedTotalSeen',
}
