export enum userSettingEnums {
    LANGUAGE = 'language',
    THEME = 'theme',
    VIEW_CHART_BY = 'viewChartBy',
    PROPOSAL_COMPARISON = 'proposalComparison',
    PROPOSAL_TYPE = 'proposalType',
    CHART_OPTIONS = 'chartOptions',
    CHART_TYPE = 'chartType',
    VIEW_HORIZONTAL = 'viewHorizontal',
    VIEW_MINI = 'viewMini', 
    VIEW_TABLE = 'viewTable',
    PROPOSAL_PDF_COLUMNS = 'proposalPdfColumns',
    GROUP_BY_CATEGORIES = 'groupByCategories',
    OG_CARD_CONFIG = 'ogCardConfig',
}