FROM dunglas/frankenphp:1.2-php8.3-alpine

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/v3.20/main" >> /etc/apk/repositories \
    && apk upgrade -U -a \
    && apk add -Uuv --no-cache \
    autoconf \
    bash \
    chromium \
    ffmpeg \
    font-noto-emoji \
    freetype \
    freetype-dev \
    gifsicle \
    gcc \
    g++ \
    git \
    harfbuzz \
    imagemagick \
    imagemagick-dev \
    jpegoptim \
    libstdc++ \
    libtool \
    libjpeg-turbo-dev \
    libzip-dev \
    libpng-dev \
    make \
    netcat-openbsd \
    postgresql-dev \
    pcre-dev \
    nginx \
    nodejs \
    npm \
    nss \
    optipng \
    pngquant \
    postgresql-client \
    supervisor \
    ttf-freefont \
    ca-certificates \
    xvfb \
    wqy-zenhei \
    && rm -rf /var/cache/apk/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser" 


RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include

RUN docker-php-ext-install -j$(nproc) pdo pdo_pgsql pgsql opcache pcntl gd bcmath posix zip exif intl

RUN printf "\n" | pecl install redis  && docker-php-ext-enable redis

RUN npm install --global --unsafe-perm puppeteer

RUN apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ && \
    yarn install

RUN apk del autoconf g++ libtool make pcre-dev

RUN apk add --update linux-headers
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && pecl install xdebug-3.3.2 \
    && apk del -f .build-deps

# && docker-php-ext-enable xdebug \



COPY ./docker/start-container /usr/local/bin/start-container

RUN chmod +x /usr/local/bin/start-container

WORKDIR /var/www

EXPOSE 8000 9003

ENTRYPOINT start-container