variables:
  AUTO_DEPLOY_IMAGE_VERSION: "v2.130.0"
  KUBE_CONTEXT: catalystexplorer
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DEPLOY_WEBAPP:
    value: "true"
    description: "Build and deploy catalystexplorer.com"
  DEPLOY_INFRA:
    value: "false"
    description: "Install infrastructure services (redis, meilisearch, postgresql)"

  WEB_BASE_IMAGE_VER:
    value: ""
    description: "New tag for WEB base image,format {version}-{yyyy-mm-dd}. eg: ubuntu-22.04-2024-10-31"

stages:
- lint
- .pre
- test
- build
- preview
- mainnet
- release

default:
  services:
  - name: docker:dind
    alias: docker
    command: [ "--tls=false" ]
  before_script:
  - |
    export APP_VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' application/package.json)
    export APP_VERSION_AND_BUILD="${APP_VERSION}-${CI_PIPELINE_ID}"
    export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE
    export CI_APPLICATION_TAG=$APP_VERSION_AND_BUILD
    
    # temporary. Remove when registry issues are resolved
    export CI_REGISTRY_USER=$REGISTRY_USER;
    export CI_REGISTRY_PASSWORD=$REGISTRY_PASSWORD;
    export CI_REGISTRY=$REGISTRY;
    export CI_APPLICATION_REPOSITORY=$APPLICATION_REPOSITORY;


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - ./node_modules

########## Lint #########
###################################

########## Pre-Build jobs #########
###################################
composer:
  stage: .pre
  image: composer:2.7
  services: []
  retry: 1
  rules:
  - if: '$DEPLOY_WEBAPP == "true"'
  dependencies:
  - yarn
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script: |-
    set -vx
    echo "$ENV_FILE"
    cp "$ENV_FILE" application/.env
    export PATH=$PATH:/usr/local/bin
    export COMPOSER_MAX_PARALLEL_HTTP=24
    export COMPOSER_FUND=0
    cd ./application
    composer config http-basic.nova.laravel.com "${NOVA_USERNAME}" "${NOVA_LICENSE_KEY}"
    composer config http-basic.satis.spatie.be "${SPATIE_AUTH_USERNAME}" "${SPATIE_AUTH_PASSWORD}"
    if [[  $CI_COMMIT_BRANCH == 'main' ]]; then
      composer install --no-scripts --no-dev --classmap-authoritative --no-interaction --no-ansi --ignore-platform-reqs
    else
      composer install --no-scripts --ignore-platform-reqs --classmap-authoritative --no-interaction --no-ansi
    fi
  artifacts:
    paths:
    - ./application/public/docs
    - ./application/vendor
    expire_in: 2 days

yarn:
  stage: .pre
  image: node:20.18.0-alpine
  services: []
  retry: 1
  rules:
  - if: '$DEPLOY_WEBAPP == "true"'
  needs:
  - composer
  before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  script: |-
    set -vx
    export PATH=$PATH:/usr/local/bin
    export NODE_OPTIONS=--max-old-space-size=8192
    cd ./application
    yarn install --ignore-engines
    yarn run build
  artifacts:
    paths:
    - ./application/public
    expire_in: 1 days

########## Automated Testing jobs #########
##############################========#####
pest:
  stage: test
  image: docker:24.0.7-dind-alpine3.18
  retry: 1
  artifacts:
    paths:
    - ./application/vendor
    expire_in: 1 days
  script:
  - |-
    set -xev
    
    if [[ -n $DOCKER_PASSWORD ]]; then
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    fi

    cp application/.env.testing application/.env

    docker-compose -f docker-compose.testing.yml up -d

    sleep 5

    docker logs catalystexplorer_test.com

    docker-compose -f docker-compose.testing.yml exec -t catalystexplorer_test.com sh -c '
     php artisan migrate:fresh --force && \
     php artisan optimize:clear  && \
     sleep 10 && \
     php artisan cx:create-search-index "App\Models\Group" && \ 
     php artisan cx:create-search-index "App\Models\Proposal" && \
     php artisan cx:create-search-index "App\Models\IdeascaleProfile" && \ 
     php artisan cx:create-search-index "App\Models\Review" && \
     php artisan cx:create-search-index "App\Models\Transaction" && \
     php artisan cx:create-search-index "App\Models\BookmarkCollection" && \
     php artisan cx:create-search-index "App\Models\Community" && \
     php artisan cx:create-search-index "App\Models\VoterHistory" && \
     sleep 10 && \
     php artisan cx:create-search-index "App\Models\MonthlyReport" && \
     php -d vendor/bin/pest'
  rules:
  - if: '$CI_COMMIT_BRANCH != "main" && ($DEPLOY_WEBAPP == "true")'
  dependencies:
  - composer
  - yarn



########## Helper Scripts ############
######################################
.auto-deploy:
  image: "${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  dependencies: []

.setup: &setup
  - apk add --no-cache ca-certificates curl bash openssl git
  - curl -LO https://dl.k8s.io/release/v1.25.9/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh && DESIRED_VERSION=v$HELM_VERSION ./get_helm.sh
  - kubectl config get-contexts
  - kubectl config use-context ${CI_TEMPLATE_REGISTRY_HOST}

.app: &app_template
  image: "${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  retry: 0
  script:
  - auto-deploy check_kube_domain
  - auto-deploy download_chart
  - auto-deploy create_secret
  - |
    DEPLOYMENT_NAME="www-catalystexplorer.$CI_ENVIRONMENT_SLUG"  
    cp $ENV_FILE ./helm/app/app_env
    cat ./helm/app/app_env
    if [ "${CI_ENVIRONMENT_NAME}" == "mainnet" ]; then
      export APP_REPLICAS="3"
      export QUEUE_REPLICAS="2"
    else
      export APP_REPLICAS="1"
      export QUEUE_REPLICAS="1"
    fi

    helm upgrade $DEPLOYMENT_NAME ./helm/app \
      --install \
      -f ./helm/app/values.yaml \
      --timeout 300s \
      --wait \
      --atomic \
      --set services.app.image.repository=$CI_APPLICATION_REPOSITORY/web-app \
      --set services.app.image.tag=$CI_APPLICATION_TAG \
      --set services.app.POSTGRESQL_WEB_DB_HOST=$POSTGRESQL_WEB_DB_HOST \
      --set services.meili.MEILISEARCH_KEY=$MEILISEARCH_KEY \
      --set services.app.environment=$APP_ENV \
      --set services.redis.password=$REDIS_PASSWORD \
      --set services.app.replicaCount=$APP_REPLICAS \
      --set services.queue.replicaCount=$QUEUE_REPLICAS \
      --set namespace=${KUBE_NAMESPACE} \
      --namespace="$KUBE_NAMESPACE" \
      --create-namespace

  - auto-deploy persist_environment_url
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  artifacts:
    paths: [ environment_url.txt ]

.db: &db_template
  stage: mainnet
  image: "${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  retry: 0
  script:
  - auto-deploy download_chart
  - |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm repo update

    echo "install db"
    helm upgrade --install \
        --timeout 300s \
        --wait \
        --atomic \
        --namespace="$KUBE_NAMESPACE" \
        --namespaceOverride="$KUBE_NAMESPACE" \
        --create-namespace \
        -f ./helm/app/values.db.yaml \
        --set global.postgresql.database="$DB_DATABASE" \
        --set global.postgresql.username="$DB_USERNAME" \
        --set global.postgresql.password="$DB_PASSWORD" \
        --set postgresql.postgresPassword="$POSTGRES_PASSWORD" \
        --set pgpool.customUsers.usernames="postgres;$DB_USERNAME" \
        --set pgpool.customUsers.passwords="$POSTGRES_PASSWORD;$DB_PASSWORD" \
        --set persistence.size="$DB_SIZE" \
        catalystexplorer-web-db \
        bitnami/postgresql-ha
  - auto-deploy persist_environment_url
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  artifacts:
    paths: [ environment_url.txt ]

.s3: &s3_template
  stage: mainnet
  image: "${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  retry: 0
  script:
  - auto-deploy download_chart
  - |
    helm repo add minio-operator https://operator.min.io
    helm repo update

    echo "install minio tenant"
    helm upgrade --install \
        --timeout 300s \
        --wait \
        --atomic \
        --namespace="catalystexplorer-minio" \
        --create-namespace \
        -f ./helm/minio/values.yaml \
        --set tenant.configSecret.accessKey="$MINIO_ACCESS_KEY" \
        --set tenant.configSecret.secretKey="$MINIO_SECRET_KEY" \
        cx-minio \
        minio-operator/tenant
  - auto-deploy persist_environment_url
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  artifacts:
    paths: [ environment_url.txt ]

.redis: &redis_template
  image: "${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  retry: 0
  script:
  - auto-deploy download_chart
  - |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm repo update

    echo "install redis"
    helm upgrade --install \
        --timeout 300s \
        --wait \
        --atomic \
        --namespace="$KUBE_NAMESPACE" \
        --create-namespace \
        -f ./helm/app/values.redis.yaml \
        --set global.redis.password="$REDIS_PASSWORD" \
        --set auth.password="$REDIS_PASSWORD" \
        --set master.persistence.enabled="true" \
        redis \
        bitnami/redis
  - auto-deploy persist_environment_url
  artifacts:
    paths: [ environment_url.txt ]

############ Build Jobs ##############
######################################
build_web:
  stage: build
  image: docker:24.0.2-git
  retry: 0
  script:
  - |
    echo "Logging in to Docker registry..."
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    docker build --network host -f ./docker/Dockerfile \
    -t "$CI_APPLICATION_REPOSITORY/web-app:$CI_APPLICATION_TAG" \
    -t "$CI_APPLICATION_REPOSITORY/web-app:latest" . 
    docker push "$CI_APPLICATION_REPOSITORY/web-app:$CI_APPLICATION_TAG" 
    docker push "$CI_APPLICATION_REPOSITORY/web-app:latest"
  rules:
    - if: '$DEPLOY_WEBAPP == "true"'
      when: manual

build_web_base:
  stage: .pre
  image: docker:24.0.2-git
  retry: 0
  script:
  - |
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY" 

    echo "Building Dockerfile with tags $CI_APPLICATION_REPOSITORY/web-app-base:$WEB_BASE_IMAGE_VER and $CI_APPLICATION_REPOSITORY/web-app-base:latest ..." 

    docker build --network host -f ./docker/Dockerfile.base \
    -t "$CI_APPLICATION_REPOSITORY/web-app-base:$WEB_BASE_IMAGE_VER" \
    -t "$CI_APPLICATION_REPOSITORY/web-app-base:latest" ./docker/. 

    docker push "$CI_APPLICATION_REPOSITORY/web-app-base:$WEB_BASE_IMAGE_VER" 
    docker push "$CI_APPLICATION_REPOSITORY/web-app-base:latest"

    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  rules:
  - if: $WEB_BASE_IMAGE_VER

######## Preview Deployments #########
######################################
db_preview:
  <<: *db_template
  stage: preview
  environment:
    name: preview
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  rules:
    - if: '$DEPLOY_INFRA == "true"'
      when: manual

redis_preview:
  <<: *redis_template
  stage: preview
  environment:
    name: preview
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  rules:
    - if: '$DEPLOY_INFRA == "true"'
      when: manual

app_preview:
  <<: *app_template
  stage: preview
  environment:
    name: preview
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  rules:
    - if: '$DEPLOY_WEBAPP == "true"'
      when: manual

######## Mainnet Deployments #########
######################################
db_mainnet:
  <<: *db_template
  stage: mainnet
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  needs:
  - job: db_preview
    optional: true
  rules:
  - if: '$CI_COMMIT_BRANCH == "main" && ($DEPLOY_INFRA == "true")'
    when: manual

s3_mainnet:
  <<: *s3_template
  stage: mainnet
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  rules:
  - if: '$CI_COMMIT_BRANCH == "main" && ($DEPLOY_INFRA == "true")'
    when: manual

redis_mainnet:
  <<: *redis_template
  stage: mainnet
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  needs:
  - job: redis_preview
    optional: true
  rules:
  - if: '$CI_COMMIT_BRANCH == "main" && ($DEPLOY_INFRA == "true")'
    when: manual

app_mainnet:
  <<: *app_template
  stage: mainnet
  environment:
    name: mainnet
    url: https://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  needs:
  - job: app_preview
  rules:
  - if: '$CI_COMMIT_BRANCH == "main" && ($DEPLOY_WEBAPP == "true")'
    when: manual

######## Semantic Releases #########
######################################
sem-release:
  stage: release
  needs:
    - job: app_mainnet
  image: node:20-alpine
  variables:
    GIT_DEPTH: 0
    GITLAB_TOKEN: ${SEMANTIC_RELEASE_GITLAB_TOKEN}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache git
    - npm install -g semantic-release @semantic-release/git @semantic-release/gitlab @semantic-release/changelog
    - git config user.name "GitLab CI"
    - git config user.email "ci@gitlab.com"
    - git remote set-url origin https://oauth2:${SEMANTIC_RELEASE_GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git config credential.helper store
    - echo "https://oauth2:${SEMANTIC_RELEASE_GITLAB_TOKEN}@${CI_SERVER_HOST}" > ~/.git-credentials
  script:
    - semantic-release
