{{- if eq .Values.services.app.environment "production" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-s3-catalystexplorer-tls
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
spec:
  secretName: wildcard-s3-catalystexplorer-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-issuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "catalystexplorer,catalystexplorer-preview,catalystexplorer-minio"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "catalystexplorer,catalystexplorer-preview,catalystexplorer-minio"
  dnsNames:
    - "*.s3.catalystexplorer.com"
{{- end -}}