{{- if eq .Values.services.app.environment "production" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Chart.Name }}-ingress-route"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: wildcard-catalystexplorer-ssl
  routes:
    - match: Host(`catalystexplorer.com`) || Host(`www.catalystexplorer.com`)
      kind: Rule
      priority: 1
      middlewares:
        - name: traefik-redirect-http-to-https@kubernetescrd
          namespace: traefik
        - name: traefik-redirect-to-www@kubernetescrd
          namespace: traefik
        - name: traefik-default-headers@kubernetescrd
          namespace: traefik
      services:
        - name: "{{ $.Chart.Name }}-app-service"
          namespace: {{ .Values.namespace }}
          port: 8000
{{- end -}}
{{- if eq .Values.services.app.environment "preview" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Chart.Name }}-ingress-route"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: wildcard-catalystexplorer-ssl
  routes:
    - match: Host(`preview.catalystexplorer.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: traefik-redirect-http-to-https@kubernetescrd
          namespace: traefik
        - name: traefik-default-headers@kubernetescrd
          namespace: traefik
      services:
        - name: "{{ $.Chart.Name }}-app-service"
          namespace: {{ .Values.namespace }}
          passHostHeader: true
          port: 8000
{{- end -}}