kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.namespace }}-web-storage-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{.Values.services.app.persistence.storageClass}}
  resources:
    requests:
      storage: {{ .Values.services.app.persistence.size }}
