# This file defines which tasks are used when parsing blocks
# Creating your own execution plan with the tasks you need for your application
# Format follows the TOML format: https://toml.io/en/

# Note: the order you specify tasks in this file matters
#       ex: if task Foo depends on task Bar, place Bar first in the list

# You can find task the task name by looking at the TASK_NAME field inside the task



[GenesisBlockTask]
readonly=false
include_payload=false

[GenesisTransactionTask]
readonly=false
include_payload=false

[MultieraBlockTask]
readonly=false
include_payload=false

[MultieraTransactionTask]
readonly=false
include_payload=false

[MultieraMetadataTask]
readonly=false
include_payload=false

[CatalystTransactionTask]
readonly=false
include_payload=true

