#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
  case "$CONTAINER_ROLE" in
    queue | q)
      php -d variables_order=EGPCS /var/www/artisan horizon
      ;;
    scheduler | s)
      while [ true ]
      do
        php /var/www/artisan schedule:run --verbose --no-interaction &
        sleep 60
      done
      ;;
    app | a)
      if [ "$OCTANE_WATCH" = "true" ]; then
        # Enable watch mode for Octane
        php -d variables_order=EGPCS /var/www/artisan octane:frankenphp --workers=1 --max-requests=50 --watch
      else
        # Run without watch mode
        php -d variables_order=EGPCS /var/www/artisan octane:frankenphp --workers=4 --max-requests=50
      fi
      ;;
    dev | d)
      mkdir -p /var/run/supervisor
      exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.dev.conf
      ;;
    *)
      echo 'this container has no role... it is a sitting duck doing nothing!'
      echo 'Please set $CONTAINER_ROLE to either queue, scheduler, or app'
      ;;
  esac
fi
