export type ProposalMetrics = {
    submitted?: number;
    approved?: number;
    completed?: number;
    inProgress?: number;
    unfunded?: number;
    funded?: number;
    requestedUSD?: number;
    requestedADA?: number;
    requestedUSDM?: number;
    awardedUSD?: number;
    awardedADA?: number;
    awardedUSDM?: number;
    distributedUSD?: number;
    distributedADA?: number;
    distributedUSDM?: number;
    completionRate?: number;
    avgRequestedADA?: number;
    avgRequestedUSD?: number;
    avgRequestedUSDM?: number;
    groupsCount?: number;
    communitiesCount?: number;
};
