import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const tableConfig: Record<string, { type: string; indexes: string }> = {
    proposal_comparisons: {
        type: 'ProposalData',
        indexes: 'id, order',
    },
    user_setting: {
        type: 'UserSettingData',
        indexes: 'language',
    },
    recently_visited_proposals: {
        type: 'RecentlyVisitedProposalData',
        indexes: 'id, visited_at',
    },
     recently_visited_lists: {
        type: 'RecentlyVisitedListData',
        indexes: 'id, visited_at',
    },
};

const outputFile = path.resolve(__dirname, '../db/generated-db-schema.ts');

const schema: Record<string, string> = {};
const modelLines: string[] = [];

for (const [tableName, config] of Object.entries(tableConfig)) {
    schema[tableName] = config.indexes;
    modelLines.push(`    "${tableName}": App.DataTransferObjects.${config.type};`);
}

const output = `// Auto-generated by generateDbSchema.ts. Do not edit manually.
//
// IMPORTANT: This file defines IndexedDB INDEXES, not columns.
// Only fields that are queried with .where() or .orderBy() need to be indexed.
// All other fields are stored but not indexed.

export const TABLE_INDEXES = ${JSON.stringify(schema, null, 4)};

export interface DbModels {
${modelLines.join('\n')}
}
`;

fs.writeFileSync(outputFile, output);
console.log('✅ DB schema generated.');