#!/usr/bin/env sh

set -e

container_role=${CONTAINER_ROLE:-"app"}

if [ "${container_role}" = "app" ]; then
    php "${ROOT}/artisan" octane:status
elif [ "${container_role}" = "horizon" ]; then
    php "${ROOT}/artisan" horizon:status
elif [ "${container_role}" = "scheduler" ]; then
    if [ "$(supervisorctl status scheduler:scheduler_0 | awk '{print tolower($2)}')" = "running" ]; then
        exit 0
    else
        echo "Healthcheck failed."
        exit 1
    fi
elif [ "${container_role}" = "reverb" ]; then
    if [ "$(supervisorctl status reverb:reverb_0 | awk '{print tolower($2)}')" = "running" ]; then
        exit 0
    else
        echo "Healthcheck failed."
        exit 1
    fi
elif [ "${container_role}" = "worker" ]; then
    if [ "$(supervisorctl status worker:worker_00 | awk '{print tolower($2)}')" = "running" ]; then
        exit 0
    else
        echo "Healthcheck failed."
        exit 1
    fi
else
    echo "Container mode mismatched."
    exit 1
fi