// Auto-generated by generateDbSchema.ts. Do not edit manually.
//
// IMPORTANT: This file defines IndexedDB INDEXES, not columns.
// Only fields that are queried with .where() or .orderBy() need to be indexed.
// All other fields are stored but not indexed.

export const TABLE_INDEXES = {
    "proposal_comparisons": "id, order",
    "user_setting": "language",
    "recently_visited_proposals": "id, visited_at",
    "recently_visited_lists": "id, visited_at"
};

export interface DbModels {
    "proposal_comparisons": App.DataTransferObjects.ProposalData;
    "user_setting": App.DataTransferObjects.UserSettingData;
    "recently_visited_proposals": App.DataTransferObjects.RecentlyVisitedProposalData;
    "recently_visited_lists": App.DataTransferObjects.RecentlyVisitedListData;
}
