declare namespace App.DataTransferObjects {
    export type GroupData = {
        id: number | null;
        user_id?: number;
        name?: string;
        bio?: Array<any>;
        slug?: string;
        status?: string;
        meta_title?: string;
        website?: string;
        twitter?: string;
        discord?: string;
        github?: string;
        created_at?: string;
        updated_at?: string;
        deleted_at?: string;
    };
    export type IdeascaleProfileData = {
        id: number | null;
        ideascaleId?: number;
        username?: string;
        email?: string;
        name?: string;
        bio?: string;
        createdAt?: string;
        updatedAt?: string;
        twitter?: string;
        linkedin?: string;
        discord?: string;
        ideascale?: string;
        claimedBy?: number;
        telegram?: string;
        title?: string;
    };
    export type ProposalData = {
        id: number | null;
        user_id: number | null;
        campaign_id: number | null;
        fund_id: number | null;
        title: Array<any> | null;
        slug: string;
        website: string | null;
        excerpt?: string;
        amount_requested: number;
        amount_received: number | null;
        definition_of_success?: string;
        status?: string;
        funding_status?: string;
        meta_data?: Array<any>;
        funded_at?: string;
        deleted_at?: string;
        funding_updated_at?: string;
        yes_votes_count: number | null;
        no_votes_count: number | null;
        abstain_votes_count: number | null;
        comment_prompt?: string;
        social_excerpt?: string;
        team_id?: number;
        ideascale_link?: string;
        type?: string;
        meta_title?: Array<any>;
        problem?: Array<any>;
        solution?: Array<any>;
        experience?: Array<any>;
        content?: Array<any>;
        currency?: string;
        opensource: boolean;
        ranking_total?: number;
        quickpitch?: string;
        quickpitch_length?: number;
    };
    export type ReviewData = {
        id: number | null;
        parent_id?: number;
        user_id?: number;
        model_id: number;
        model_type: string;
        title?: string;
        content: string;
        status: string | null;
        published_at?: string;
        type: string;
        ranking_total: number;
        helpful_total: number;
        not_helpful_total: number;
    };
    export type ReviewModerationData = {
        id: number | null;
        reviewer_id?: number;
        excellent_count: number;
        good_count: number;
        filtered_out_count: number;
        flagged: boolean;
        qa_rationale?: Array<any>;
    };
    export type UserData = {
        id: number;
        name: string;
        email: string;
        profile_photo_url: string;
        email_verified_at: string;
    };
}
