declare namespace App.DataTransferObjects {
export type AnnouncementData = {
hash: string;
title: string;
content: string;
label?: string;
context?: string;
event_starts_at?: string;
event_ends_at?: string;
cta?: object;
user_id: number;
hero_image_url: string;
};
export type BookmarkCollectionData = {
hash: string | null;
user_id?: number;
parent_id?: number;
title?: string;
content?: string;
color?: string;
allow_comments?: string;
visibility?: string;
status?: string;
type?: string;
type_id?: number;
type_type?: string;
created_at?: string;
updated_at?: string;
deleted_at?: string;
};
export type BookmarkItemData = {
hash: string | null;
user_id?: number;
bookmark_collection_id?: number;
model_id?: number;
model_type?: string;
title?: string;
content?: string;
action?: number;
created_at?: string;
updated_at?: string;
deleted_at?: string;
};
export type CampaignData = {
hash: string | null;
fund_id?: number;
title: string;
meta_title: string | null;
slug: string | null;
excerpt?: string;
comment_prompt?: string;
content?: string;
hero_img_url?: string;
amount: number | null;
created_at: string | null;
updated_at: string | null;
label?: string;
currency: string;
proposals_count: number | null;
unfunded_proposals_count: number | null;
funded_proposals_count: number | null;
completed_proposals_count: number | null;
total_requested: number | null;
total_awarded: number | null;
total_distributed: number | null;
};
export type CommunityData = {
hash: string | null;
title?: string;
content?: string;
user_id?: number;
status?: string;
slug?: string;
created_at?: string;
updated_at?: string;
deleted_at?: string;
};
export type ConnectionData = {
nodes: Array<App.DataTransferObjects.ConnectionNodeData>;
links: Array<App.DataTransferObjects.ConnectionLinkData>;
rootNodeId: string;
rootNodeHash: string;
rootNodeType: string;
};
export type ConnectionLinkData = {
source: string;
target: string;
};
export type ConnectionNodeData = {
id: string;
type: string;
name: string;
hash?: string;
photo?: string;
val?: number;
x?: number;
y?: number;
};
export type FundData = {
amount: number | null;
label: string | null;
title: string;
hash: string | null;
proposals_count?: number;
funded_proposals_count?: number;
completed_proposals_count?: number;
amount_requested?: number;
amount_awarded?: number;
meta_title?: string;
slug?: string;
user_id?: number;
excerpt?: string;
comment_prompt?: string;
content?: string;
hero_img_url?: string;
banner_img_url?: string;
status?: string;
launched_at?: string;
awarded_at?: string;
color?: string;
currency?: string;
review_started_at?: string;
parent_id?: number;
};
export type GroupData = {
hash: string | null;
user_id?: number;
name?: string;
hero_img_url?: string;
bio?: string;
banner_img_url?: string;
slug?: string;
status?: string;
meta_title?: string;
website?: string;
twitter?: string;
discord?: string;
github?: string;
linkedin?: string;
created_at?: string;
updated_at?: string;
deleted_at?: string;
amount_awarded_ada?: number;
amount_awarded_usd?: number;
amount_requested_ada?: number;
amount_requested_usd?: number;
amount_distributed_ada?: number;
amount_distributed_usd?: number;
proposals_count?: number;
completed_proposals_count?: number;
funded_proposals_count?: number;
unfunded_proposals_count?: number;
proposals_funded?: number;
proposals_unfunded?: number;
proposals_completed?: number;
ideascale_profiles?: Array<any>;
reviews?: number;
};
export type IdeascaleProfileData = {
hash: string | null;
ideascaleId?: number;
username?: string;
email?: string;
name?: string;
bio?: Array<any> | string | null;
createdAt?: string;
updatedAt?: string;
twitter?: string;
linkedin?: string;
discord?: string;
ideascale?: string;
claimedBy?: number;
telegram?: string;
title?: string;
hero_img_url?: string;
amount_awarded_usd?: number;
amount_awarded_ada?: number;
amount_requested_ada?: number;
amount_requested_usd?: number;
amount_distributed_ada?: number;
amount_distributed_usd?: number;
co_proposals_count?: number;
own_proposals_count?: number;
claimed_by?: number;
completed_proposals_count?: number;
funded_proposals_count?: number;
unfunded_proposals_count?: number;
proposals_count?: number;
collaborating_proposals_count?: number;
};
export type LocationData = {
hash: string | null;
country: string;
city: string;
region?: string;
street?: string;
address_1?: string;
address_2?: string;
lat?: number;
long?: number;
};
export type MetricData = {
hash: string | null;
user_id: number | null;
title: string;
content?: string;
status?: string;
created_at?: string;
updated_at?: string;
color?: string;
field?: string;
type: string;
query: string;
count_by?: string;
chartData?: Array<any>;
value?: number;
order?: number;
};
export type PostData = {
id: number | null;
title: string | null;
subtitle: string | null;
summary: string | null;
hero: any;
author_gravatar: string | null;
author_name: string | null;
link: string;
read_time: string | null;
type: string | null;
published_at?: string;
};
export type ProposalData = {
hash: string | null;
campaign: App.DataTransferObjects.CampaignData | null;
title: string | null;
slug: string | null;
website?: string;
excerpt?: string;
content?: any;
amount_requested?: number;
amount_received?: number;
definition_of_success?: string;
status: string;
funding_status?: string;
funded_at?: string;
deleted_at?: string;
funding_updated_at?: string;
yes_votes_count?: number;
no_votes_count?: number;
abstain_votes_count?: number;
comment_prompt?: string;
social_excerpt?: string;
ideascale_link?: string;
projectcatalyst_io_link?: string;
type?: string;
meta_title?: string;
problem?: string;
solution?: string;
experience?: string;
currency?: string;
ranking_total?: number;
quickpitch?: string;
quickpitch_length?: number;
users: any | null;
fund: App.DataTransferObjects.FundData | null;
opensource: boolean | null;
link?: string;
};
export type ReviewData = {
hash: string | null;
parent_id?: number;
user_id?: number;
model_id: number | null;
model_type: string | null;
title?: string;
content: string;
status: string | null;
published_at?: string;
type: string | null;
ranking_total: number | null;
helpful_total: number | null;
not_helpful_total: number | null;
};
export type ReviewModerationData = {
hash: string | null;
reviewer_id?: number;
excellent_count: number;
good_count: number;
filtered_out_count: number;
flagged: boolean;
qa_rationale?: Array<any>;
};
export type UserData = {
hash: string;
name: string;
email: string;
hero_img_url: string | null;
email_verified_at: string | null;
locations: any | null;
};
}
