export type ProposalSearchParams = {
    AWARDED_ADA: string,
    AWARDED_USD: string,
    BUDGETS: string,
    CATEGORIES: string,
    CAMPAIGNS: string,
    COHORT: string,
    COMMUNITIES: string,
    FUNDS: string,
    FUNDING_STATUS: string,
    GROUPS: string,
    LIMIT: string,
    MAX_BUDGET: string,
    MAX_PROJECT_LENGTH: string,
    MIN_BUDGET: string,
    MIN_PROJECT_LENGTH: string,
    OPENSOURCE_PROPOSALS: string,
    PAGE: string,
    PEOPLE: string,
    PROJECT_STATUS: string,
    QUERY: string,
    QUICK_PITCHES: string,
    VIEW: string,
    SORTS: string,
    TAGS: string,
    TYPE: string,
}
