import { ProposalParamsEnum } from '@/enums/proposal-search-params';

export type ProposalSearchParams = {
    length: number;
    [ProposalParamsEnum.AWARDED_ADA]: number[];
    [ProposalParamsEnum.AWARDED_USD]: number[];
    [ProposalParamsEnum.BUDGETS]: number[];
    [ProposalParamsEnum.CATEGORIES]: string;
    [ProposalParamsEnum.CAMPAIGNS]: string[];
    [ProposalParamsEnum.COHORT]: string[];
    [ProposalParamsEnum.COMMUNITIES]: string[];
    [ProposalParamsEnum.FUNDS]: string[];
    [ProposalParamsEnum.FUNDING_STATUS]: (string[] | string);
    [ProposalParamsEnum.GROUPS]: string[];
    [ProposalParamsEnum.LIMIT]: number;
    [ProposalParamsEnum.MAX_BUDGET]: number;
    [ProposalParamsEnum.MAX_PROJECT_LENGTH]: number;
    [ProposalParamsEnum.MIN_BUDGET]: number;
    [ProposalParamsEnum.MIN_PROJECT_LENGTH]: number;
    [ProposalParamsEnum.OPENSOURCE_PROPOSALS]: string;
    [ProposalParamsEnum.PAGE]: number;
    [ProposalParamsEnum.IDEASCALE_PROFILES]: string[];
    [ProposalParamsEnum.PROJECT_STATUS]: string[];
    [ProposalParamsEnum.QUERY]: string;
    [ProposalParamsEnum.QUICK_PITCHES]: string;
    [ProposalParamsEnum.VIEW]: string;
    [ProposalParamsEnum.SORTS]: string[];
    [ProposalParamsEnum.TAGS]: string[];
    [ProposalParamsEnum.TYPE]: string;
    [ProposalParamsEnum.PROJECT_LENGTH]: number[];
    [key: string]: any; 
};
